#' Compute Ratio of Relative Abundance
#'
#' This function computes the ratio of relative abundance of cell lines between a control group
#' (e.g., DMSO) and treatment groups. The ratios are derived from fractions estimated using a
#' Dirichlet-multinomial Bayesian approach. These ratios can be combined with tumor volume or
#' confluency data to estimate treatment resistance. Results are visualized using violin plots
#' to illustrate the distribution of relative abundances.
#'
#' @param model A list containing the results of the `GPI` function, including:
#'   - `names_cell`: Vector of cell line names.
#'   - `control_group`: Name of the control group (e.g., "DMSO").
#'   - `condition_count`: Vector of condition names (e.g., "Control", "Treatment").
#'   - `n_sam`: Number of posterior samples.
#'   - `L`: Number of cell types.
#'   - `K`: Number of conditions.
#' @param sampled_fraction A list of matrices containing sampled fractions for each condition,
#'   as generated by the `PPC_count` function. These fractions are estimated from the
#'   Dirichlet-multinomial Bayesian model.
#' @param q_up Upper quantile threshold for filtering extreme values (default: 0.975).
#' @param q_lo Lower quantile threshold for filtering extreme values (default: 0.025).
#'
#' @return A list containing:
#'   - `plot_ratio_fraction`: A ggplot object visualizing the ratio of relative abundance across conditions.
#'   - `li_sam_ratio_relative`: A list of matrices containing the computed ratios of relative abundance.
#'
#' @examples
#' # Example usage:
#' # model <- list(names_cell = c("Cell1", "Cell2"),
#' #               control_group = "Control",
#' #               condition_count = c("Control", "Treatment"),
#' #               n_sam = 10, L = 2, K = 2)
#' # sampled_fraction <- list(matrix(1:12, 3, 4), matrix(13:24, 3, 4))
#' # ratio_plot <- Ratio_Fraction(model, sampled_fraction)
#' # print(ratio_plot$plot_ratio_fraction)
#'
#' @import ggplot2 dplyr
#' @export
Ratio_Fraction <- function(model, sampled_fraction, q_up = 0.975, q_lo = 0.025) {
  # Ensure sampled_fraction exists
  if (is.null(sampled_fraction)) {
    stop("sampled_fraction is not available. Run PPC_count() first.")
  }

  # Extract necessary model details
  cell <- unique(model$names_cell)
  control_group <- model$control_group
  condition_count <- model$condition_count
  n_sam <- model$n_sam
  L <- model$L
  K <- model$K

  # Validate control group
  if (is.null(control_group)) {
    control_group <- unique(condition_count)[1]
    message("Control group not specified. Defaulting to the first condition: ", control_group)
  } else if (!(control_group %in% condition_count)) {
    stop("The specified control_group must be present in condition_count.")
  }

  # Initialize storage for relative abundance ratios
  li_sam_ratio_relative <- list()
  jj <- 1
  rep_per_cell <- table(model$names_cell)  # Number of repetitions per cell line

  # Compute ratios for each condition
  for (k in 1:K) {
    expmus <- sampled_fraction[[k]]
    expmus2 <- matrix(0, nrow = nrow(expmus), ncol = L)  # Empty matrix to store summed fractions

    # Summing fractions for each cell line
    for (l in 1:L) {
      start_col <- (l - 1) * rep_per_cell[l] + 1
      end_col <- l * rep_per_cell[l]
      expmus2[, l] <- rowSums(expmus[, start_col:end_col, drop = FALSE])

    }

    # Identify the control group matrix
    if (any(unique(condition_count)[k] %in% control_group)) {
      expmus_ref <- expmus2
    }

    # Compute the ratio relative to the control group
    if (!any(unique(condition_count)[k] %in% control_group)) {
      li_sam_ratio_relative[[jj]] <- expmus2 / (expmus_ref + 10^(-10))
      jj <- jj + 1
    }
  }

  # Assign names to the ratios list
  names(li_sam_ratio_relative) <- setdiff(unique(condition_count), control_group)
  li_sam <- unlist(li_sam_ratio_relative)

  # Prepare data for visualization
  treatt <- rep(names(li_sam_ratio_relative), each = L * n_sam)
  celll <- rep(rep(cell, each = n_sam), length(names(li_sam_ratio_relative)))
  data_g <- data.frame(p_ratio = log(li_sam), treat = treatt, cell = celll)
  threshold <- 0

  # Filter the data based on quantiles
  filtered_data1 <- data_g %>%
    group_by(treat, cell) %>%
    mutate(a = ifelse(p_ratio <= quantile(p_ratio, q_up) &
                        p_ratio >= quantile(p_ratio, q_lo), p_ratio, NA)) %>%
    na.omit() %>%
    ungroup()

  # Generate the plot
  plot_ratio_fraction <- ggplot(filtered_data1, aes(x = factor(cell, levels = unique(cell)),
                                                    y = p_ratio,
                                                    fill = factor(cell, levels = unique(cell)))) +
    geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), scale = "width", trim = FALSE) +
    facet_wrap(~ factor(treat, levels = unique(treat))) +
    geom_hline(yintercept = threshold, linetype = "dashed", color = "blue", size = 2) +
    labs(x = "Cell line",
         y = "Ratio of relative abundance (log scale)",
         fill = "Cell line") +
    theme(axis.text.x = element_text(face = "bold", size = 18, angle = 45, hjust = 1),
          axis.text.y = element_text(face = "bold", size = 18),
          axis.title.x = element_text(face = "bold", size = 18),
          axis.title.y = element_text(face = "bold", size = 18),
          strip.text = element_text(face = "bold", size = 18),
          plot.title = element_text(size = 20, hjust = 0.5, vjust = 0.5),
          plot.margin = margin(20, 20, 40, 40),
          legend.title = element_text(size = 18),
          legend.text = element_text(size = 15))

  return(list(plot_ratio_fraction = plot_ratio_fraction, li_sam_ratio_relative = li_sam_ratio_relative))
}
